# Generated by Django 5.0.3 on 2026-09-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_batch_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at']},
        ),
    ]
